"""Generate the proof leaderboard from optional library-index provenance.

Usage:
  python3 -m tools.leaderboard [<repo-root>]
  python3 -m tools.leaderboard --check [<repo-root>]
"""
from __future__ import annotations

import statistics
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from tools.gate_b.records import parse_record


@dataclass(frozen=True)
class Proof:
    goal: str
    date: str
    solver: str | None
    agent: str | None
    provider: str | None
    model: str | None
    effort: str | None
    attempts: int | None
    solve_s: int | None
    difficulty: int


def _optional(value: str | None) -> str | None:
    return None if not value or value == "∅" else value


def _integer(value: str | None) -> int | None:
    return int(value) if value and value.isdigit() else None


def proofs(root: Path) -> list[Proof]:
    difficulty: dict[str, int] = {}
    for path in sorted((root / "goals").glob("*.aisp")):
        record = parse_record(path.read_text(encoding="utf-8"))
        raw = record.fields.get("difficulty", "0")
        difficulty[path.stem] = int(raw) if raw.isdigit() else 0

    result: list[Proof] = []
    for path in sorted((root / "library" / "index").glob("*.aisp")):
        record = parse_record(path.read_text(encoding="utf-8"))
        goal = record.fields.get("goal", path.stem)
        result.append(
            Proof(
                goal=goal,
                date=record.header.date if record.header else "",
                solver=_optional(record.fields.get("solver")),
                agent=_optional(record.fields.get("agent")),
                provider=_optional(record.fields.get("provider")),
                model=_optional(record.fields.get("model")),
                effort=_optional(record.fields.get("effort")),
                attempts=_integer(record.fields.get("attempts")),
                solve_s=_integer(record.fields.get("solve_s")),
                difficulty=difficulty.get(goal, 0),
            )
        )
    return result


def _duration(values: list[int]) -> str:
    if not values:
        return "—"
    seconds = int(statistics.median(values))
    minutes, seconds = divmod(seconds, 60)
    hours, minutes = divmod(minutes, 60)
    if hours:
        return f"{hours}h {minutes}m"
    if minutes:
        return f"{minutes}m {seconds}s"
    return f"{seconds}s"


def render(root: Path) -> str:
    data = proofs(root)
    attributed = [proof for proof in data if proof.solver and proof.provider]
    historical = len(data) - len(attributed)

    by_solver: dict[str, list[Proof]] = defaultdict(list)
    by_model: dict[str, list[Proof]] = defaultdict(list)
    for proof in attributed:
        assert proof.solver and proof.provider
        by_solver[proof.solver].append(proof)
        model = proof.model or "unknown"
        by_model[f"{proof.provider} / {model}"].append(proof)

    lines = [
        "# Proof Leaderboard",
        "",
        "<!-- generated by tools/leaderboard/generate.py — do not edit by hand -->",
        "",
        "Counts come only from kernel-verified `library/index` entries. Provenance is "
        "optional and advisory: it never affects proof soundness, selection, or admission. "
        "Historical records are not guessed from squash-merge authorship.",
        "",
        f"**{len(data)} verified proofs · {len(attributed)} attributed · "
        f"{historical} historical/unknown.**",
        "",
        "## Contributors",
        "",
        "| Rank | GitHub solver | Proofs | Difficulty points | Median solve time |",
        "|-----:|---------------|-------:|------------------:|------------------:|",
    ]
    solver_rows = sorted(
        by_solver.items(),
        key=lambda item: (-len(item[1]), -sum(p.difficulty for p in item[1]), item[0].lower()),
    )
    if not solver_rows:
        lines.append("| — | No attributed proofs yet | — | — | — |")
    for rank, (solver, items) in enumerate(solver_rows, 1):
        times = [p.solve_s for p in items if p.solve_s is not None]
        lines.append(
            f"| {rank} | [@{solver}](https://github.com/{solver}) | {len(items)} | "
            f"{sum(p.difficulty for p in items)} | {_duration(times)} |"
        )

    lines.extend([
        "",
        "## Models",
        "",
        "| Provider / model | Verified proofs | Solvers | Median solve time |",
        "|------------------|----------------:|--------:|------------------:|",
    ])
    model_rows = sorted(by_model.items(), key=lambda item: (-len(item[1]), item[0]))
    if not model_rows:
        lines.append("| No attributed proofs yet | — | — | — |")
    for label, items in model_rows:
        solvers = len({p.solver for p in items if p.solver})
        times = [p.solve_s for p in items if p.solve_s is not None]
        lines.append(f"| `{label}` | {len(items)} | {solvers} | {_duration(times)} |")

    lines.extend([
        "",
        "## Attributed Proofs",
        "",
        "| Goal | Solver | Agent | Provider / model | Attempts | Solve time |",
        "|------|--------|-------|------------------|---------:|-----------:|",
    ])
    if not attributed:
        lines.append("| No attributed proofs yet | — | — | — | — | — |")
    for proof in sorted(attributed, key=lambda p: (p.date, p.goal), reverse=True):
        model = proof.model or "unknown"
        attempts = str(proof.attempts) if proof.attempts is not None else "—"
        solve = _duration([proof.solve_s]) if proof.solve_s is not None else "—"
        lines.append(
            f"| `{proof.goal}` | [@{proof.solver}](https://github.com/{proof.solver}) | "
            f"`{proof.agent or 'unknown'}` | `{proof.provider} / {model}` | "
            f"{attempts} | {solve} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    check = "--check" in argv
    rest = [arg for arg in argv if arg != "--check"]
    root = Path(rest[0]) if rest else Path.cwd()
    content = render(root)
    target = root / "docs" / "leaderboard.md"
    if check:
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current != content:
            print(
                "docs/leaderboard.md is stale — regenerate with "
                "`python3 -m tools.leaderboard > docs/leaderboard.md`",
                file=sys.stderr,
            )
            return 1
        return 0
    sys.stdout.write(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
